### ISSUE TITLE
Error when running Forwarding.uc

### ISSUE THREAD

**Issue by mikeazo** [easyuc/EasyUC#2]
I've got a fresh install of EasyCrypt and latest code from the repository. When I try to run `bin/ucdsl examples/sessions/Forwarding.uc`, however, I get an error about _Sessions_.

```
[error: examples/sessions/Forwarding.uc: from line 6 columns 14 to 24]

EasyCrypt: In external theory Forwarding
[Forwarding.ec: line 1 (0) to line 6 (23)]: cannot locate theory `Sessions'
```

All other `.uc` files work just fine, so maybe I am just running things incorrectly on this one.

**Comment by alleystoughton** [comment]
Thanks for the feedback, Mike. I had forgotten to push Sessions.ec to the repo. Now done.

**Comment by mikeazo** [comment]
Thanks! Works great now.
