### ISSUE TITLE
interpreter client should exit with message if interpreter raises unexpected exception

### ISSUE THREAD

**Issue by alleystoughton** [easyuc/EasyUC#22]
The interpreter client seems to be catching exceptions like `Assert_failure` and `Invalid_argument`, but then ignoring them. Instead, I think the client should exit letting the user know what exception was raised. In the case of assertion failures, we have the file position of the problem, which the user (or programmer) doesn't learn about. I could be printed before exit.

**Comment by 01tomislav** [comment]
Exit when non-error_message exception happens, also when running in PG. Change build to show stack trace with uncaught exception.
