### ISSUE TITLE
combine various flags for interpreter behavior in UcState into one data type

### ISSUE THREAD

**Issue by 01tomislav** [easyuc/EasyUC#23]

**Comment by alleystoughton** [comment]
This includes the -raw flag, which only makes sense for the Emacs major mode for editing .uc files. Looking at simplifying the flow of control in ucdsl.ml at the same time makes sense.

**Comment by alleystoughton** [comment]
After looking at the code and making some simplifications, I don't think we need to combine raw_msg and pg_mode.
