### ISSUE TITLE
race condition when proof general starts up

### ISSUE THREAD

**Issue by alleystoughton** [easyuc/EasyUC#29]
When proof general starts up, and a load is done, I sometimes find that the `var` command in

```
load SMC2.
functionality
  SMC2.SMC2Real
  (SMC.SMCReal(KeyExchange.KEReal),
  SMC.SMCReal(KeyExchange.KEReal)).
var text : text.
```

fails, saying `text` was already added. But when I redo the `load`, it works. I guess this is a proof general thing where the addition of the variable was run through the interpreter, but proof general doesn't know it should have advanced past it.

**Comment by 01tomislav** [comment]
This only happens when opening the uci file for the second time in the same emacs session. I noticed that quitting emacs between opening uci files prevents this from happening.

**Comment by 01tomislav** [comment]
I could not reproduce the race condition. However, same errors happen when uc-frame is deleted (red x button clicked). Somehow selecting a deleted frame does not result in exception, instead the code that fills current buffer, which should be the buffer shown in uc-frame, instead fills script buffer, and we get parsing exception from ucInterpreter.
Please see if this also solves race condition.

**Comment by alleystoughton** [comment]
I still have the race condition, but I don't think this is a problem. The user will learn to let the first `load` bring up the UC file frame before continuing.
