### ISSUE TITLE
Issue with DSL ./configure

### ISSUE THREAD

**Issue by Hiltzaile6** [easyuc/EasyUC#3]
When attempting to run ./configure in the UC DSL setup, I was getting an error stating that I needed to run it from the uc-dsl directory, despite already being in that directory. By commenting out the check lines in ./configure, I was able to bypass the check and complete setup.

**Comment by alleystoughton** [comment]
Thanks for the report. The script was looking for the old copyright file, which no longer exists. I've updated it to look for the new `LICENSE` file instead.

**Comment by alleystoughton** [comment]
Thanks for the report. The script was looking for the old copyright file, which no longer exists. I've updated it to look for the new LICENSE file instead.
