### ISSUE TITLE
execution getting progressively slower as script gets longer

### ISSUE THREAD

**Issue by alleystoughton** [easyuc/EasyUC#32]
It seems that execution getting progressively slower as script gets longer.

**Comment by alleystoughton** [comment]
Sometimes it takes minutes for anything to happen. We need to figure out if this is a proof general thing or something in the interpreter.

**Comment by alleystoughton** [comment]
I'm watching testing.uci with -debug turned on, and after a while pretty printing of configurations is coming out a little bit at a time. Could we be running out of memory? Or maybe we have a bunch of SMT solving processes?

**Comment by alleystoughton** [comment]
48G of memory for ucdsl according to `top`

**Comment by 01tomislav** [comment]
The client keeps a growing stack of configuration. Still, a single configuration would need to be about 1G to get to 48G.

**Comment by alleystoughton** [comment]
The only component of configurations that might be growing in the real world is a map from relative addresses to states of functionalities - which in the case of a real functionality is in turn a map from party ids to states. I just instrumented the code to check this wasn't growing. It's holding fast at 31 entries, summing across the maps.

**Comment by alleystoughton** [comment]
See the branch interpreter-memory-leak for a version of the interpreter that does smt calls in a loop as part of creating an initial general configuration.

interpreter-memory-leak:

```
    This branch is for diagnosing the memory leak in the interpreter.
    I added the following code to UcInterpreter.create_gen_config. After
    just a load the memory usage was 164MB.
    
    let form =
      envport_form (addr_concat_form func_form (addr_make_form [1;2;3]))
      adv_form (make_port_form func_form (int_form 1)) in
    let rec run_smt n =
      if n = 0
      then ()
      else ((try ignore (eval_bool_form_to_bool gc pi dbs (f_not form)) with
             | ECProofEngine -> ());
            run_smt (n - 1)) in
    let () = run_smt 10000 in
```
    
    I aborted the above after a while, when the memory had gone up to
    65GB. So it seems clear there is a memory leak in how we are doing
    SMT calls.

**Comment by alleystoughton** [comment]
The garbage collection fix is working, so closing this.
