### ISSUE TITLE
issue with simplification via rewriting

### ISSUE THREAD

**Issue by alleystoughton** [easyuc/EasyUC#37]
In smc2-ping-adv, the testing.uci script now takes one to the point of a match failure having to do with simplification via rewriting. With debugging on, we get

```
trying to simplify formula:

epdp_text_key.`dec
(epdp_text_key.`enc text1 ^^ (g ^ rand1 ^ rand) ^^ kinv (g ^ rand ^ rand1))




result is:

epdp_text_key.`dec
(epdp_text_key.`enc text1 ^^ (g ^ rand1 ^ rand) ^^ kinv (g ^ rand ^ rand1))




trying to deconstruct formula:

epdp_text_key.`dec
(epdp_text_key.`enc text1 ^^ (g ^ rand1 ^ rand) ^^ kinv (g ^ rand ^ rand1))




deconstruction by simplification failed.
 
         Trying to simplify by evaluating get_as_Constr




deconstruction failed
```

(We should clean up these messages generated by UcEcFormEval.)

Running epdp and then uc_dsl_interpreter_hints turns the above into text1.

**Comment by 01tomislav** [comment]
it should have been ucdsl_interpreter_hints instead of uc_dsl_interpreter_hints, as the one_time_dh is then not the part of the ucdsl_interpreter_hints rewrite database which is used as the source of hints.

**Comment by alleystoughton** [comment]
Yeah, after noticing the problem, I changed the name (but not in both places - good catch) because of our restrictions on legal ids. Otherwise one can't remove or add it via the new command.
