### ISSUE TITLE
Error when building EasyUC DSL

### ISSUE THREAD

**Issue by Hiltzaile6** [easyuc/EasyUC#4]
When attempting to run ./build for the EasyUC DSL, I am running into the following error:

File "src/ucParser.mly", line 473, characters 27-36:
Error: This expression has type fun_param list
       but an expression was expected of type 'a located

Interested to see if you can recreate this bug. I have not run into it in the past when building your tool.

**Comment by Hiltzaile6** [comment]
Just attempted a `build-cleanup` followed by a `build`, to no avail.
My pull is up to date, and I am running ocaml version 4.13.1

**Comment by alleystoughton** [comment]
I'm running ocaml 4.12.1. You could try initializing opam with

```
opam switch create 4.12.1
```

I haven't tried building even easycrypt with 4.13.1.

**Comment by Hiltzaile6** [comment]
Still running into that issue after switching ocaml versions.

Including my setup process to see if I am doing something wrong there:

git clone https://github.com/easyuc/EasyUC

sudo apt-get install ocaml
sudo apt-get install opam

opam init
eval $(opam env)

opam install batteries
opam install dune
opam install bisect_ppx

sudo apt-get install ocaml-native-compilers camlp4-extra
opam pin -yn add easycrypt https://github.com/EasyCrypt/easycrypt.git
opam install opam-depext
opam depext easycrypt
opam install --deps-only easycrypt
opam install alt-ergo
opam install easycrypt
easycrypt why3config

./configure

./build

**Comment by alleystoughton** [comment]
I don't do `sudo apt-get install ocaml-native-compilers camlp4-extra`. The instructions I follow are in `https://alleystoughton.us/easycrypt-installation.html`.

I did an `opam update`, `opam upgrade`, and things still work for me. I'm not sure what's going on for you. And the type error message you are getting doesn't make sense to me - and, well, I don't see why another compiler version would make a difference.

Did you change platforms or something, with respect to when it used to work for you?

It's getting late in my current time zone (Israel), so I probably won't respond more this evening.

**Comment by Hiltzaile6** [comment]
I believe I have found the issue. Alt-Ergo released a new version on August 4th, 2022 (version 2.4.2) which seems to be incompatible if you run `easycrypt why3config`. This would explain why the build process worked on my old VM, but not my new one.

Changing my alt-ergo version back to 2.4.1 or 2.4.0 resolved the issue and the build completes successfully. Thank you for your help!

**Comment by alleystoughton** [comment]
OK, thanks for this information. I'll see if I can figure out why runing `easycrypt why3config` has any affect on the ucdsl build process. Running ucdsl should no longer depend upon this configuration...

**Comment by Hiltzaile6** [comment]
Does the build process rely on alt-ergo? It could be the case that simply downgrading alt-ergo to a previous version fixed the issue.

**Comment by alleystoughton** [comment]
Well, it shouldn't, because why3 is an intermediary. I'll see if I can figure out what's going on when I get home to Boston.
