### ISSUE TITLE
In interpreter, how do I add to the ucdsl command line options

### ISSUE THREAD

**Issue by mikeazo** [easyuc/EasyUC#41]
When running `M-x compile` on a `.uc` file I have the opportunity to edit the command line options of the `ucdsl` executable.

When running the interpreter, however, I am never given such an option. If I have `.ec` files in a separate folder, that means I cannot include them in the search path.

**Comment by alleystoughton** [comment]
EasyCrypt uses the Emacs directory local variables mechanism for this: https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html

Here is an example, where "smart_counter" is a subdirectory of the main directory. In the file `.dir-locals.el` there is

```
((easycrypt-mode .
  ((eval .
    (cl-flet ((pre (s) (concat (locate-dominating-file buffer-file-name ".dir-locals.el") s)))
           (setq easycrypt-load-path `(,(pre ".") ,(pre "smart_counter"))))))))
```

This is automatically searching for .dir-local.el in the parent directory.

Making our users edit such files is kind of low level, but we might use such a solution.

**Comment by alleystoughton** [comment]
Notes for UC DSL developers.

I think it's simpler to use

```
$ less .dir-locals.el 
;;; Directory Local Variables            -*- no-byte-compile: t -*-
;;; For more information see (info "(emacs) Directory Variables")

(
 (easycrypt-mode .
  ((easycrypt-load-path . ("../../prelude"))))
)
```

as the contents of the `.dir-locals.el` file. The above is how we customize the EasyCrypt load path (supplying `-I` command line argument to the EasyCrypt executable), in this case to include just single directory. In general, this can have a list of strings.

So what we need to do is replicate the code for processing the path in `easycrypt.el` in `ucInterpreter.el`.

So then we can have, e.g.,

```
(
 (easycrypt-mode .
  ((easycrypt-load-path . ("../../prelude"))))
 (ucInterpreter-mode .
  ((ucInterpreter-load-path . ("../../prelude"))))
)
```
