### ISSUE TITLE
Problem loading UC file in Proof General, UC DSL Interpreter mode

### ISSUE THREAD

**Issue by uguryavuz** [easyuc/EasyUC#48]
There seems to a problem when UC DSL Interpreter is started by Proof General via "process the next proof command". When running [uc-dsl/examples/smc2/testing.uci](https://github.com/easyuc/EasyUC/blob/master/uc-dsl/examples/smc2/testing.uci) in Emacs, this is what I observe after processing the load line.

<img width="794" alt="image" src="https://github.com/easyuc/EasyUC/assets/35351115/403adf35-3738-4787-9bb0-6e8d128fa013">

I cannot process the file further, getting a "parse error." 

<img width="794" alt="image" src="https://github.com/easyuc/EasyUC/assets/35351115/1012e1a2-139f-43f4-9160-43c893fc5ab9">

The issue is not present if the Interpreter has been launched beforehand, nor on the command line.

**Comment by alleystoughton** [comment]
Note that this user is running macOS on an M1 Mac, and using the GUI version of Emacs (just like me). Somehow the text `*** no code running ***` which should be in the `*UC file` frame is ending up in the `*uc dsl interpreter*` buffer after the initial `load`.

**Comment by alleystoughton** [comment]
OK, the user confirms that running `open -a emacs testing.uci` doesn't cause the problem. The problem occurs if one starts up emacs and then types `C-x C-f RET` and completes the path to `testing.uci`. Then the frame names are messed up. This weirdness doesn't occur with EasyCrypt's proof general code.

**Comment by alleystoughton** [comment]
This problem comes up for me if I first visit a `.uc` file, and then do `C-x C-f RET` and select a `.uci` file. The main frame is then called `*UC file*`. When the initial `load` is done, then the text `*** no code running ***` is put in the `*uc dsl interpreter*` buffer.

**Comment by alleystoughton** [comment]
Something is still not quite right here. If I start emacs, and then visit smc2/testing.uci, I get the following frames:

<img width="1728" alt="Screenshot 2023-11-28 at 12 37 56 PM" src="https://github.com/easyuc/EasyUC/assets/9660498/88155d41-ee83-48e3-ba68-94e483e26f11">

`ucdsl-file-buffer` has also been created, but I have to bring it manually up. Things then work, but this isn't ideal.

**Comment by alleystoughton** [comment]
Despite fix, still getting behavior in previous screenshots.
