### ISSUE TITLE
Display version/build info in startup message

### ISSUE THREAD

**Issue by rpgrahamjr941** [easyuc/EasyUC#54]
When starting `ucdsl` (from the command line or in Proof General), display version and build information (e.g., commit). See what EasyCrypt does for an example.

**Comment by alleystoughton** [comment]
As of commit f9a802bc3c4b4a35227912a55bd3e35c18bc8257, there is a new ucdsl option, -version, which prints the EasyUC Git commit from which the build was done.

We're not using versioning yet for this project. And I don't think we need to print the commit in ProofGeneral.

(By the way, the build information provided by EasyCrypt, at least for me, is not giving the commit I did the build from.)
